plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  tag:Name: project-1-app

keyed_groups:
  - key: tags.Name
    prefix: tag
    separator: "_"

hostnames:
  - private-ip-address

